# Generated by Django 5.1.4 on 2024-12-29 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('sequence', models.IntegerField()),
                ('is_mandatory', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('linkedin_profile', models.URLField()),
                ('emails', models.JSONField(default=list)),
                ('phone_numbers', models.JSONField(default=list)),
                ('comments', models.TextField(blank=True)),
                ('communication_periodicity', models.IntegerField(default=14)),
            ],
        ),
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('notes', models.TextField()),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_module.communicationmethod')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_module.company')),
            ],
        ),
    ]
