# Generated by Django 5.1.4 on 2024-12-29 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='communication',
            name='status',
            field=models.CharField(choices=[('overdue', 'Overdue'), ('completed', 'Completed'), ('scheduled', 'Scheduled')], max_length=20, null=True),
        ),
    ]
