# Generated by Django 5.1.4 on 2024-12-29 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0002_communication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='communication',
            name='due_date',
            field=models.DateTimeField(null=True),
        ),
    ]
